
# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the server script and the main_images directory into the container
COPY server.py .
COPY main_images/ main_images/

# Install Flask
RUN pip install Flask

# Expose the port the app runs on
EXPOSE 65432

# Command to run the server script
CMD ["python", "./server.py"]
