# Dockerfile_client
FROM python:3.8-slim

WORKDIR app

# Copy required files
COPY grpc_client.py /app
COPY imagesearch_pb2.py /app
COPY imagesearch_pb2_grpc.py /app

# Install gRPC and protobuf
RUN pip install grpcio protobuf

CMD ["python", "grpc_client.py"]
